name: 14-caching
on:
  workflow_dispatch:
    inputs:
      cache-deps:
        description: Whether or not to use cache
        type: boolean
        default: true
      node-version:
        description: node version selection
        type: choice
        options:
          - 20.x
          - 21.x
          - 22.x
          - 23.x
          - 24.x
          - 25.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 1-caching/react-app
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{inputs.node-version}}
      - name: Download cache deps
        uses: actions/cache@v3
        if: ${{inputs.cache-deps}}
        id: cache
        with:
          key: npm-${{ hashFiles('1-caching/react-app/package-lock.json') }}
          path: 1-caching/react-app/node_modules
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci
      - name: Testing
        run: |
          npm run test
      - name: Build
        run: |
          npm run build
      - name: Deploy to non-prod
        run: |
          echo "Deploy to non-prod"
