name: 16-Matrices
on: workflow_dispatch
jobs:
  backwards-compatibility:
    name: ${{matrix.os-version}}-${{matrix.node-version}}
    runs-on: ${{matrix.os-version}}
    strategy:
      matrix:
        node-version: [20.x, 21.x, 22.x]
        os-version:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: setup-node
        uses: actions/setup-node@v4
        with: ${{ matrix.node-version }}
      - name: Perform some task
        run: echo "Running test on os ${{matrix.os-version}} on node ${{matrix.node-version}}"
