name: working with environment
run-name: Execution on ${{inputs.target-env}}
on:
  workflow_dispatch:
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: echo vars
        run: |
          echo "Env Varuialbe : ${{vars.MY_VAR || 'Default value'}}"
  E2E_testing:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: E2E testing
        run: |
          echo "Running E2E testing"
  deploy-prod-frontend:
    runs-on: ubuntu-latest
    environment: prod
    needs: [deploy-staging, E2E_testing]
    steps:
      - name: deploy production
        run: echo "Deploying prod frontend"
  deploy-prod-backend1:
    runs-on: ubuntu-latest
    environment: prod
    needs: [deploy-staging, E2E_testing]
    steps:
      - name: deploy production
        run: echo "Deploying prod backend1"
  deploy-prod-backend2:
    runs-on: ubuntu-latest
    environment: prod
    needs: [deploy-staging, E2E_testing]
    steps:
      - name: deploy production
        run: echo "Deploying prod backend2"
