name: 18-composit action
run-name: target env is ${{inputs.target-env}}
on:
  workflow_dispatch:
    inputs:
      target-env:
        default: "dev"
        description: "which env to target dev or prod"
        type: choice
        options:
          - dev
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      path: 3-custom-action/react-app
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node and npm deps
        uses: ./.github/actions/conposite-action-deps
        with:
          node-version: 23.x
          working-directory: ${{env.path}}
          target-env: ${{inputs.target-env}}
      - name: Testing
        run: npm run test
        working-directory: ${{env.path}}
      - name: Build
        run: npm run build
        working-directory: ${{env.path}}
