name: 20-2-reusable workflow
on: workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/20-1-reusable-workflow.yml
    with:
      target-directory: dummy-dir

  print-outputs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print output
        run: |
          echo "Build status ${{needs.deploy.outputs.build-status}}" 
          echo "Build url ${{needs.deploy.outputs.url}}"
